/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "ble_canonical_service.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Canonical Service packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Canonical Service packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_RX_PORT_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted rx_port. */ 
#define MAX_TX_PORT_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted tx_port. */ 


/**@brief Function for encoding rx_port.
 *
 * @param[in]   p_rx_port              rx_port characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t rx_port_encode(ble_canonical_service_rx_port_t * p_rx_port, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_rx_port->field_1, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for decoding rx_port.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
//static uint8_t rx_port_decode(uint8_t data_len, uint8_t * p_data, ble_canonical_service_rx_port_t * p_write_val)
//{
//    uint8_t pos = 0;
//    pos += bds_uint8_array_decode((data_len-pos), &p_data[pos], &p_write_val->field_1);
//
//    return pos;
//}
/**@brief Function for encoding tx_port.
 *
 * @param[in]   p_tx_port              tx_port characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t tx_port_encode(ble_canonical_service_tx_port_t * p_tx_port, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_tx_port->field_1, &encoded_buffer[len]); 
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_canonical_service       Canonical Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_canonical_service_t * p_canonical_service, ble_evt_t * p_ble_evt)
{
    p_canonical_service->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}


/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_canonical_service       Canonical Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_canonical_service_t * p_canonical_service, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_canonical_service->conn_handle = BLE_CONN_HANDLE_INVALID;
}


/**@brief Function for handling the Write event.
 *
 * @param[in]   p_canonical_service       Canonical Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_canonical_service_t * p_canonical_service, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_canonical_service->rx_port_handles.value_handle)
    {
        if(p_canonical_service->evt_handler != NULL)
        {
            ble_canonical_service_evt_t evt;
            // no buffer allocated prior to rx_port_decode() call ... ???
            evt.evt_type = BLE_CANONICAL_SERVICE_RX_PORT_EVT_WRITE;

            // TODO create a pool allocator here for rx buffers
            static uint8_t rx_buffer[20];
            evt.params.rx_port.field_1.p_data = rx_buffer;
            evt.params.rx_port.field_1.size = p_ble_evt->len;
            //rx_port_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.rx_port);
//            static uint8_t rx_port_decode(uint8_t data_len, uint8_t * p_data, ble_canonical_service_rx_port_t * p_write_val)
//            {
//                uint8_t pos = 0;
//                pos += bds_uint8_array_decode((data_len-pos), &p_data[pos], &p_write_val->field_1);
//
//                return pos;
//            }
//            static __INLINE uint8_t bds_uint8_array_decode(const uint8_t len,
//                                                           const uint8_t * p_encoded_data,
//                                                           uint8_array_t * p_decoded_val)
//            {
//                memcpy(p_decoded_val->p_data, p_encoded_data, len);
//                p_decoded_val->size = len;
//                return p_decoded_val->size;
//            }
            memcpy(evt.params.rx_port.field_1.p_data, p_ble_evt->data, p_ble_evt->len);

            p_canonical_service->evt_handler(p_canonical_service, &evt);
        }
    }
    if(p_ble_evt->handle == p_canonical_service->tx_port_handles.cccd_handle)
    {
        if(p_canonical_service->evt_handler != NULL)
        {
            ble_canonical_service_evt_t evt;
            evt.evt_type = BLE_CANONICAL_SERVICE_TX_PORT_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_canonical_service->evt_handler(p_canonical_service, &evt);
        }
    } 
}


/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_canonical_service_t * p_canonical_service, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}


/**@brief Function for handling BLE events.
 *
 * @param[in]   p_canonical_service       Canonical Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_canonical_service_on_ble_evt(ble_canonical_service_t * p_canonical_service, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_canonical_service, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_canonical_service, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_canonical_service, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_canonical_service, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Canonical Service. */
uint32_t ble_canonical_service_init(ble_canonical_service_t * p_canonical_service, const ble_canonical_service_init_t * p_canonical_service_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_canonical_service->evt_handler = p_canonical_service_init->evt_handler;
    p_canonical_service->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x6C, 0x6C, 0x8F, 0xA4, 0x72, 0x59, 0x30, 0x99, 0xB1, 0x4D, 0x74, 0x1C, 0x00, 0x00, 0xC5, 0x20}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x93E4;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_canonical_service->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add rx_port characteristic
    ble_canonical_service_rx_port_t rx_port_initial_value = p_canonical_service_init->ble_canonical_service_rx_port_initial_value; 

    uint8_t rx_port_encoded_value[MAX_RX_PORT_LEN];
    ble_add_char_params_t add_rx_port_params;
    memset(&add_rx_port_params, 0, sizeof(add_rx_port_params));
    
    add_rx_port_params.uuid                = 0x2195;
    add_rx_port_params.uuid_type           = ble_uuid.type; 
    add_rx_port_params.max_len             = MAX_RX_PORT_LEN;
    add_rx_port_params.init_len            = rx_port_encode(&rx_port_initial_value, rx_port_encoded_value);
    add_rx_port_params.p_init_value        = rx_port_encoded_value; 
    add_rx_port_params.char_props.write_wo_resp    = 1; 
    add_rx_port_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_rx_port_params.is_var_len          = 1; 

    err_code = characteristic_add(p_canonical_service->service_handle, &add_rx_port_params, &(p_canonical_service->rx_port_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add tx_port characteristic
    ble_canonical_service_tx_port_t tx_port_initial_value = p_canonical_service_init->ble_canonical_service_tx_port_initial_value; 

    uint8_t tx_port_encoded_value[MAX_TX_PORT_LEN];
    ble_add_char_params_t add_tx_port_params;
    memset(&add_tx_port_params, 0, sizeof(add_tx_port_params));
    
    add_tx_port_params.uuid                = 0x4E02;
    add_tx_port_params.uuid_type           = ble_uuid.type; 
    add_tx_port_params.max_len             = MAX_TX_PORT_LEN;
    add_tx_port_params.init_len            = tx_port_encode(&tx_port_initial_value, tx_port_encoded_value);
    add_tx_port_params.p_init_value        = tx_port_encoded_value; 
    add_tx_port_params.char_props.notify   = 1; 
    add_tx_port_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_tx_port_params.is_var_len          = 1; 

    err_code = characteristic_add(p_canonical_service->service_handle, &add_tx_port_params, &(p_canonical_service->tx_port_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}


/**@brief Function for sending the tx_port. */
uint32_t ble_canonical_service_tx_port_send(ble_canonical_service_t * p_canonical_service, ble_canonical_service_tx_port_t * p_tx_port)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_canonical_service->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_TX_PORT_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = tx_port_encode(p_tx_port, encoded_value);
        hvx_params.handle = p_canonical_service->tx_port_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_canonical_service->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}
