/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "canonical_service_if.h"
#include <stdint.h>
#include "nrf_log.h"
#include "ble_canonical_service.h" 

static ble_canonical_service_t m_canonical_service;

//#define SIZE_BLE_PACKET 20
uint8_t m_canonical_service_rx_port_initial_value_field_1_arr[SIZE_BLE_PACKET];
uint8_t m_canonical_service_tx_port_initial_value_field_1_arr[SIZE_BLE_PACKET];


/**@brief Function for handling the Canonical Service events.
 *
 * @details This function will be called for all Canonical Service events which are passed to
 *          the application.
 *
 * @param[in]   p_canonical_service   Canonical Service structure.
 * @param[in]   p_evt   Event received from the Canonical Service.
 */
static void on_canonical_service_evt(ble_canonical_service_t * p_canonical_service, ble_canonical_service_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_CANONICAL_SERVICE_RX_PORT_EVT_WRITE:
        	NRF_LOG_INFO("[Bluetooth_IF]: CANONICAL_SERVICE_RX_PORT evt WRITE. \r\n");
        	NRF_LOG_INFO("  size: %d\r\n", p_evt->params.rx_port.field_1.size);
            for (size_t i = 0; i < p_evt->params.rx_port.field_1.size; ++i)
            {
            	NRF_LOG_INFO("  %2x", p_evt->params.rx_port.field_1.p_data[i]);
            }
            NRF_LOG_INFO("\r\n");
            break; 
        case BLE_CANONICAL_SERVICE_TX_PORT_EVT_NOTIFICATION_ENABLED:
        	NRF_LOG_INFO("[Bluetooth_IF]: CANONICAL_SERVICE_TX_PORT evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_CANONICAL_SERVICE_TX_PORT_EVT_NOTIFICATION_DISABLED:
        	NRF_LOG_INFO("[Bluetooth_IF]: CANONICAL_SERVICE_TX_PORT evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_CANONICAL_SERVICE_TX_PORT_EVT_CCCD_WRITE:
        	NRF_LOG_INFO("[Bluetooth_IF]: CANONICAL_SERVICE_TX_PORT evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t canonical_bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_canonical_service_init_t    canonical_service_init; 
    
    // Initialize Canonical Service.
    memset(&canonical_service_init, 0, sizeof(canonical_service_init));

    canonical_service_init.evt_handler = on_canonical_service_evt; 
    canonical_service_init.ble_canonical_service_rx_port_initial_value.field_1.size = SIZE_BLE_PACKET;
    canonical_service_init.ble_canonical_service_rx_port_initial_value.field_1.p_data = m_canonical_service_rx_port_initial_value_field_1_arr; 
    canonical_service_init.ble_canonical_service_tx_port_initial_value.field_1.size = SIZE_BLE_PACKET;
    canonical_service_init.ble_canonical_service_tx_port_initial_value.field_1.p_data = m_canonical_service_tx_port_initial_value_field_1_arr; 

    err_code = ble_canonical_service_init(&m_canonical_service, &canonical_service_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void canonical_bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_canonical_service_on_ble_evt(&m_canonical_service, p_ble_evt); 
}


uint32_t canonical_send(uint8_t* p_data)
{
    uint32_t err_code = NRF_SUCCESS;

    ble_canonical_service_tx_port_t canonical_service_tx;
    canonical_service_tx.field_1.size = SIZE_BLE_PACKET;
    canonical_service_tx.field_1.p_data = p_data;

    err_code = ble_canonical_service_tx_port_send(&m_canonical_service, &canonical_service_tx);

    return err_code;
}
