/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#ifndef BLE_DEBUG_SERVICE_H__
#define BLE_DEBUG_SERVICE_H__

#include <stdint.h>
#include <stdbool.h>
#include "ble.h"
#include "ble_srv_common.h"
#include "app_util_bds.h"


/**@brief Debug Service event type. */
typedef enum
{ 
    BLE_DEBUG_SERVICE_CONTROL_EVT_NOTIFICATION_ENABLED,  /**< control value notification enabled event. */
    BLE_DEBUG_SERVICE_CONTROL_EVT_NOTIFICATION_DISABLED, /**< control value notification disabled event. */
    BLE_DEBUG_SERVICE_CONTROL_EVT_WRITE, /**< control write event. */
    BLE_DEBUG_SERVICE_LOG_EVT_NOTIFICATION_ENABLED,  /**< log value notification enabled event. */
    BLE_DEBUG_SERVICE_LOG_EVT_NOTIFICATION_DISABLED, /**< log value notification disabled event. */
    BLE_DEBUG_SERVICE_LOG_EVT_CCCD_WRITE, /**< log CCCD write event. */
} ble_debug_service_evt_type_t;

// Forward declaration of the ble_debug_service_t type.
typedef struct ble_debug_service_s ble_debug_service_t;

/**@brief control structure. */
typedef struct
{
    uint8_array_t field_1;
} ble_debug_service_control_t;

/**@brief log structure. */
typedef struct
{
    uint8_array_t field_1;
} ble_debug_service_log_t;

/**@brief Debug Service Service event. */
typedef struct
{
    ble_debug_service_evt_type_t evt_type;    /**< Type of event. */
    union {
        uint16_t cccd_value; /**< Holds decoded data in Notify and Indicate event handler. */
        ble_debug_service_control_t control; /**< Holds decoded data in Write event handler. */
    } params;
} ble_debug_service_evt_t;

/**@brief Debug Service Service event handler type. */
typedef void (*ble_debug_service_evt_handler_t) (ble_debug_service_t * p_debug_service, ble_debug_service_evt_t * p_evt);

/**@brief Debug Service Service init structure. This contains all options and data needed for initialization of the service */
typedef struct
{
    ble_debug_service_evt_handler_t	evt_handler; /**< Event handler to be called for handling events in the Debug Service Service. */
     ble_debug_service_control_t 	ble_debug_service_control_initial_value; /**< If not NULL, initial value of the control characteristic. */
     ble_debug_service_log_t 		ble_debug_service_log_initial_value; /**< If not NULL, initial value of the log characteristic. */
} ble_debug_service_init_t;

/**@brief Debug Service Service structure. This contains various status information for the service.*/
struct ble_debug_service_s
{
    ble_debug_service_evt_handler_t evt_handler; /**< Event handler to be called for handling events in the Debug Service Service. */
    uint16_t service_handle; /**< Handle of Debug Service Service (as provided by the BLE stack). */
    ble_gatts_char_handles_t control_handles; /**< Handles related to the control characteristic. */
    ble_gatts_char_handles_t log_handles; /**< Handles related to the log characteristic. */
    uint16_t conn_handle; /**< Handle of the current connection (as provided by the BLE stack, is BLE_CONN_HANDLE_INVALID if not in a connection). */
};

/**@brief Function for initializing the Debug Service.
 *
 * @param[out]  p_debug_service       Debug Service Service structure. This structure will have to be supplied by
 *                          the application. It will be initialized by this function, and will later
 *                          be used to identify this particular service instance.
 * @param[in]   p_debug_service_init  Information needed to initialize the service.
 *
 * @return      NRF_SUCCESS on successful initialization of service, otherwise an error code.
 */
uint32_t ble_debug_service_init(ble_debug_service_t * p_debug_service, const ble_debug_service_init_t * p_debug_service_init);

/**@brief Function for handling the Application's BLE Stack events.*/
void ble_debug_service_on_ble_evt(ble_debug_service_t * p_debug_service, ble_evt_t * p_ble_evt);

/**@brief Function for sending the log.
 *
 * @details The application calls this function after having performed a log.
 *          The log data is encoded and sent to the client.
 *          This function is only generated if the characteristic's Notify or Indicate property is not 'Excluded'.
 *
 * @param[in]   p_debug_service                    Debug Service Service structure.
 * @param[in]   p_log               New log.
 *
 * @return      NRF_SUCCESS on success, otherwise an error code.
 */
uint32_t ble_debug_service_log_send(ble_debug_service_t * p_debug_service, ble_debug_service_log_t * p_log);

#endif //_BLE_DEBUG_SERVICE_H__
