/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "ble_debug_service.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside Debug Service packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside Debug Service packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_CONTROL_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted control. */ 
#define MAX_LOG_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted log. */ 


/**@brief Function for encoding control.
 *
 * @param[in]   p_control              control characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t control_encode(ble_debug_service_control_t * p_control, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_control->field_1, &encoded_buffer[len]);
    return len;
}


///**@brief Function for decoding control.
// *
// * @param[in]   data_len              Length of the field to be decoded.
// * @param[in]   p_data                Buffer where the encoded data is stored.
// * @param[out]  p_write_val           Decoded data.
// *
// * @return      Length of the decoded field.
// */
//static uint8_t control_decode(uint8_t data_len, uint8_t * p_data, ble_debug_service_control_t * p_write_val)
//{
//    uint8_t pos = 0;
//
//    return pos;
//}


/**@brief Function for encoding log.
 *
 * @param[in]   p_log              log characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t log_encode(ble_debug_service_log_t * p_log, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_log->field_1, &encoded_buffer[len]);
    return len;
}


/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_debug_service       Debug Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_debug_service_t * p_debug_service, ble_evt_t * p_ble_evt)
{
    p_debug_service->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}


/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_debug_service       Debug Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_debug_service_t * p_debug_service, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_debug_service->conn_handle = BLE_CONN_HANDLE_INVALID;
}


/**@brief Function for handling the Write event.
 *
 * @param[in]   p_debug_service       Debug Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_debug_service_t * p_debug_service, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_debug_service->control_handles.value_handle)
    {
        if(p_debug_service->evt_handler != NULL)
        {
            ble_debug_service_evt_t evt;
            evt.evt_type = BLE_DEBUG_SERVICE_CONTROL_EVT_WRITE;
//            control_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.control);

            // TODO create a pool allocator here for control buffers
            static uint8_t rx_buffer[20];
            evt.params.control.field_1.p_data = rx_buffer;
            evt.params.control.field_1.size = p_ble_evt->len;
            memcpy(evt.params.control.field_1.p_data, p_ble_evt->data, p_ble_evt->len);

            p_debug_service->evt_handler(p_debug_service, &evt);
        }
    }
    if(p_ble_evt->handle == p_debug_service->log_handles.cccd_handle)
    {
        if(p_debug_service->evt_handler != NULL)
        {
            ble_debug_service_evt_t evt;
            evt.evt_type = BLE_DEBUG_SERVICE_LOG_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_debug_service->evt_handler(p_debug_service, &evt);
        }
    } 
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_debug_service_t * p_debug_service, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_debug_service       Debug Service Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_debug_service_on_ble_evt(ble_debug_service_t * p_debug_service, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_debug_service, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_debug_service, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_debug_service, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_debug_service, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the Debug Service. */
uint32_t ble_debug_service_init(ble_debug_service_t * p_debug_service, const ble_debug_service_init_t * p_debug_service_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_debug_service->evt_handler = p_debug_service_init->evt_handler;
    p_debug_service->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x67, 0xA2, 0x32, 0xBF, 0x1C, 0x27, 0x5A, 0xBC, 0xA6, 0x47, 0xFC, 0x45, 0x00, 0x00, 0xE0, 0x54}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0x8701;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_debug_service->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add control characteristic
    ble_debug_service_control_t control_initial_value = p_debug_service_init->ble_debug_service_control_initial_value;

    uint8_t control_encoded_value[MAX_CONTROL_LEN];
    ble_add_char_params_t add_control_params;
    memset(&add_control_params, 0, sizeof(add_control_params));
    
    add_control_params.uuid                = 0x28A5;
    add_control_params.uuid_type           = ble_uuid.type; 
    add_control_params.max_len             = MAX_CONTROL_LEN;
    add_control_params.init_len            = control_encode(&control_initial_value, control_encoded_value);
    add_control_params.p_init_value        = control_encoded_value; 
    add_control_params.char_props.write_wo_resp    = 1; 
    add_control_params.write_access        = SEC_OPEN; 
    // 1 for variable length and 0 for fixed length.
    add_control_params.is_var_len          = 1; 

    err_code = characteristic_add(p_debug_service->service_handle, &add_control_params, &(p_debug_service->control_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add log characteristic
    ble_debug_service_log_t log_initial_value = p_debug_service_init->ble_debug_service_log_initial_value;

    uint8_t log_encoded_value[MAX_LOG_LEN];
    ble_add_char_params_t add_log_params;
    memset(&add_log_params, 0, sizeof(add_log_params));
    
    add_log_params.uuid                = 0x0733;
    add_log_params.uuid_type           = ble_uuid.type; 
    add_log_params.max_len             = MAX_LOG_LEN;
    add_log_params.init_len            = log_encode(&log_initial_value, log_encoded_value);
    add_log_params.p_init_value        = log_encoded_value; 
    add_log_params.char_props.notify   = 1; 
    add_log_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_log_params.is_var_len          = 1; 

    err_code = characteristic_add(p_debug_service->service_handle, &add_log_params, &(p_debug_service->log_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for sending the log. */
uint32_t ble_debug_service_log_send(ble_debug_service_t * p_debug_service, ble_debug_service_log_t * p_log)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_debug_service->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_LOG_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = log_encode(p_log, encoded_value);
        hvx_params.handle = p_debug_service->log_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_debug_service->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

