/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "debug_service_if.h"
#include <stdint.h>
#include "nrf_log.h"
#include "ble_debug_service.h" 

static ble_debug_service_t    m_debug_service; 

// TODO make common define
//#define SIZE_BLE_PACKET 20
uint8_t m_debug_service_control_initial_value_field_1_arr[SIZE_BLE_PACKET];
uint8_t m_canonical_service_log_initial_value_field_1_arr[SIZE_BLE_PACKET];


/**@brief Function for handling the Debug Service events.
 *
 * @details This function will be called for all Debug Service events which are passed to
 *          the application.
 *
 * @param[in]   p_debug_service   Debug Service structure.
 * @param[in]   p_evt   Event received from the Debug Service.
 */
static void on_debug_service_evt(ble_debug_service_t * p_debug_service, ble_debug_service_evt_t * p_evt)
{
    switch (p_evt->evt_type)
    { 
        case BLE_DEBUG_SERVICE_CONTROL_EVT_WRITE:
        	NRF_LOG_INFO("[Bluetooth_IF]: DEBUG_SERVICE_CONTROL evt WRITE. \r\n");
        	NRF_LOG_INFO("  size: %d\r\n", p_evt->params.control.field_1.size);
            for (size_t i = 0; i < p_evt->params.control.field_1.size; ++i)
            {
            	NRF_LOG_INFO("  %2x", p_evt->params.control.field_1.p_data[i]);
            }
            NRF_LOG_INFO("\r\n");
            break; 
        case BLE_DEBUG_SERVICE_LOG_EVT_NOTIFICATION_ENABLED:
        	NRF_LOG_INFO("[Bluetooth_IF]: DEBUG_SERVICE_LOG evt NOTIFICATION_ENABLED. \r\n");
            break;
        case BLE_DEBUG_SERVICE_LOG_EVT_NOTIFICATION_DISABLED:
        	NRF_LOG_INFO("[Bluetooth_IF]: DEBUG_SERVICE_LOG evt NOTIFICATION_DISABLED. \r\n");
            break;
        case BLE_DEBUG_SERVICE_LOG_EVT_CCCD_WRITE:
        	NRF_LOG_INFO("[Bluetooth_IF]: DEBUG_SERVICE_LOG evt CCCD_WRITE. \r\n");
            break; 
        default:
            // No implementation needed.
            break;
    }
}


/**@brief Function for initializing the Services generated by Bluetooth Developer Studio.
 *
 *
 * @return      NRF_SUCCESS on successful initialization of services, otherwise an error code.
 */
uint32_t debug_bluetooth_init(void)
{
    uint32_t    err_code; 
    ble_debug_service_init_t    debug_service_init;

    // Initialize Debug Service.
    memset(&debug_service_init, 0, sizeof(debug_service_init));

    debug_service_init.evt_handler = on_debug_service_evt; 
    debug_service_init.ble_debug_service_control_initial_value.field_1.size = SIZE_BLE_PACKET;
    debug_service_init.ble_debug_service_control_initial_value.field_1.p_data = m_debug_service_control_initial_value_field_1_arr;
    debug_service_init.ble_debug_service_log_initial_value.field_1.size = SIZE_BLE_PACKET;
    debug_service_init.ble_debug_service_log_initial_value.field_1.p_data = m_canonical_service_log_initial_value_field_1_arr;

    err_code = ble_debug_service_init(&m_debug_service, &debug_service_init);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for handling the Application's BLE Stack events.
 *
 * @details Handles all events from the BLE stack of interest to all Bluetooth Developer Studio generated Services.
 *
 * @param[in]   p_ble_evt  Event received from the BLE stack.
 */
void debug_bluetooth_on_ble_evt(ble_evt_t * p_ble_evt)
{ 
    ble_debug_service_on_ble_evt(&m_debug_service, p_ble_evt); 
}


uint32_t debug_send(uint8_t* p_data)
{
    uint32_t err_code = NRF_SUCCESS;

    ble_debug_service_log_t debug_service_log;
    debug_service_log.field_1.size = SIZE_BLE_PACKET;
    debug_service_log.field_1.p_data = p_data;

    err_code = ble_debug_service_log_send(&m_debug_service, &debug_service_log);

    return err_code;
}
